CREATE TABLE IF NOT EXISTS
Categories (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Parent INTEGER DEFAULT -1 NOT NULL,
	Name TEXT NOT NULL,
	Expanded BOOLEAN
);

CREATE INDEX IF NOT EXISTS
	Categories_parent
ON
	Categories(Parent);


CREATE TABLE IF NOT EXISTS Components (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Category INTEGER NOT NULL,
	Name TEXT NOT NULL,
	New_amount INTEGER DEFAULT 0,
	Recycled_amount INTEGER DEFAULT 0,
	Template TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS
	components_category
ON
	Components(Category);


CREATE TABLE IF NOT EXISTS Components_Data (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Component INTEGER NOT NULL,
	Key TEXT NOT NULL,
	Value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS
	components_data_component
ON
	Components_Data(Component);
	
	
CREATE TABLE IF NOT EXISTS Images (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Parent INTEGER NOT NULL,
	Category BOOLEAN NOT NULL,
	Image BLOB NOT NULL
);

CREATE INDEX IF NOT EXISTS
	components_data_component
ON
	Components_Data(Component);


CREATE TABLE IF NOT EXISTS Datasheets (
	Component INTEGER NOT NULL UNIQUE,
	File BLOB NOT NULL,
	Extension TEXT(8) NOT NULL
);

CREATE INDEX IF NOT EXISTS
	Datasheets_component
ON
	Datasheets(Component);